const LL = "LL";
const XX = "XX";

map = [LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,
       LL,40,XX,XX,35,XX,XX,XX,XX,XX,XX,XX,XX,24,XX,XX,XX,XX,XX,XX,XX,XX,09,XX,XX,05,LL,
       LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,
       LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,
       LL,39,XX,XX,34,LL,LL,31,XX,XX,XX,XX,XX,23,XX,XX,XX,XX,XX,14,LL,LL,08,XX,XX,04,LL,
       LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,
       LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,
       LL,XX,LL,LL,LL,LL,LL,30,XX,XX,26,XX,XX,22,XX,XX,16,XX,XX,13,LL,LL,LL,LL,LL,XX,LL,
       LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,LL,21,LL,LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,
       LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,
       LL,38,XX,XX,XX,XX,XX,29,LL,LL,XX,LL,LL,XX,LL,LL,XX,LL,LL,12,XX,XX,XX,XX,XX,03,LL,
       LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,
       LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,LL,20,LL,LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,
       LL,XX,LL,LL,LL,LL,LL,28,XX,XX,25,XX,XX,19,XX,XX,15,XX,XX,11,LL,LL,LL,LL,LL,XX,LL,
       LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,
       LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,XX,LL,
       LL,37,XX,XX,33,LL,LL,27,XX,XX,XX,XX,XX,18,XX,XX,XX,XX,XX,10,LL,LL,07,XX,XX,02,LL,
       LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,
       LL,XX,LL,LL,XX,LL,LL,LL,LL,LL,LL,LL,LL,XX,LL,LL,LL,LL,LL,LL,LL,LL,XX,LL,LL,XX,LL,
       LL,36,XX,XX,32,XX,XX,XX,XX,XX,XX,XX,XX,17,XX,XX,XX,XX,XX,XX,XX,XX,06,XX,XX,01,LL,
       LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL,LL];

module.exports = map;